# Site settings
name: Helene's blog
email: 878723827@qq.com
author: Helene
url: http://www.thisisme1228.com
github: https://github.com/Thisisme1228
baseurl: ""
description: 纵然疾风起，我心飞扬
meta_description: 厚积薄发
motto: 别空有皮囊
banner: 一日不读书便觉得面目可憎了
better_me: Better me

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Thisisme1228

