# Site settings
name: This is me
email: 878723827@qq.com
author: 王丹
url: http://www.thisisme1228.com
github: https://github.com/Thisisme1228
baseurl: ""
description: 我很激动，以至于不知道写啥好，以至于你看见的除了空白还是空白，这样的时候不会很久，不是说过段时间我不喜欢了，而是我需要适应一下这期待已久的个人网站
meta_description: 厚积薄发
motto: 别空有皮囊
banner: 一日不读书便觉得面目可憎了

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Thisisme1228

