# Site settings
name: Helene's blog
email: 878723827@qq.com
author: Helene
url: http://www.thisisme1228.com
github: https://github.com/Thisisme1228
baseurl: ""
description: 纵然疾风起，人生不言弃
meta_description: 厚积薄发
motto: Better me
banner:  唐僧开场白：“贫僧唐三藏，从东土大唐而来，去往西天取经”《初心易得，始终难守》
better_me: Helene's Blog

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Thisisme1228

